### ISSUE TITLE
Marauder agent DIRECT Transport comunication error path

### ISSUE THREAD

**Issue by Tru5tNo1** [maraudershell/Marauder#5]
Describe the bug
Marauders Agent DIRECT Transport (debug mode)  Got response: ERROR

Error Message

(2019-05-16T13:35:49.2758384+02:00) [TransportService] - Starting Loop..
(2019-05-16T13:35:49.2758384+02:00) [TransportService] - Clearing Completed Tasks..
(2019-05-16T13:35:49.2758384+02:00) [CryptoService] - Creating Staging Message..
(2019-05-16T13:35:49.2758384+02:00) [CryptoService] - Clearing Response Queue
(2019-05-16T13:35:49.2758384+02:00) [CryptoService] - Raw Json: {"StagingId":"mT6N2WCP","Username":"EVL-W10-vm\\LOCALUSER","Hostname":"EVL-W10-vm","OperatingSystem":"Microsoft Windows NT 6.2.9200.0","PID":1516,"Admin":false,"InternalIP":null}
[Marauder DIRECT Transport] Staging URL: 172.10.1.145/api/v1/staging/jXsQECyTU4s/mT6N2WCP/
[Marauder DIRECT Transport] Key Name: LLr9Seb4Ku3fgLop
[Marauder DIRECT Transport] Secret: VkGAgbEjQm-Z4edUOmbpRikONhhdEPuj-3Ef_5PX46GxUf8UscAJQxZpNIE5BHim
[Marauder DIRECT Transport] Sending Staging Message: {"TransportId": 1,"Message": "eyJQYXlsb2FkTmFtZSI6ImpYc1FFQ3lUVTRzIiwiSVYiOiJLR3pkd1ZMazNLaG5QTVpnZ3ZKZTlBPT0iLCJNZXNzYWdlIjoiWHp5MHp0a3IrRGpuYUJlYlJjRW0wb2hCVS9tdUM4a09kUS8xYi9JTE5NQXpldXJZZkF4MGY3ZGVPTjR6V2Q3SDhPQW9jVHNoaG9RL3dQWHEwYjFUNDVvYVBiRjFHbU4zZUZjQmFLb3NFWWR4Vkh1M2RrMkNZS3UyVjlNMWZ4amJCbFRScUw5SGNuS042KzFVQjdjUUlvMzllY2JaZXZWRzdZUkRqbnMxNkYyVTJzSzJ1U0V6djFUK3JFbTBjRHp6QlVQZ2JXWE5yQ1duaEorbFlpcEJyZXVybEpTMW84YWtvUkNyUUFIUTM2cDF4UWpMek1FclpvaTAxLzZORlpPUiIsIkhNQUMiOiJ1cXFTVXIzOC9icHFOZnpLVVkreFhQRGFnSnB4Y0lHK1BwaSs2U3EzZlA0PSJ9"}
[Marauder DIRECT Transport] Got ERROR: Impossibile trovare una parte del percorso 'C:\Users\LOCALUSER\Desktop\172.10.1.145\api\v1\staging\jXsQECyTU4s\mT6N2WCP\'.
(2019-05-16T13:35:49.2907187+02:00) [TransportService] - Got response: ERROR

To Reproduce
Launch a new Marauder agent on  Windows 10 Vm

Execute:
C:\Users\LOCALUSER\Desktop>Marauder_Default_jXsQEC[...snip...]0516095341.exe

Desktop:
Windows 10 ver 1803 build 17134.320 (VmWare 15 Vm)

**Comment by jaredhaight** [comment]
Did you use the `--external-address` parameter when running `faction setup`? Looks like it was set with an IP address (172.10.1.145) instead of a full url (https://172.10.1.145). This is probably the problem here. Try that and see if it fixes the issue for you.

We need to add a check to the CLI catch this, cause its easy to mess up.

**Comment by Tru5tNo1** [comment]
It works !!!! 
Thank you,  best regards ;)

**Comment by jaredhaight** [comment]
Yay! Happy to hear that!
